# Generated by Django 3.1.4 on 2024-07-21 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='GPSlocation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='NivEduc',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='QteBoisChauffage',
            field=models.IntegerField(default=0, help_text='la quantité approximative de bois de chauffage en kg/mois '),
        ),
        migrations.AddField(
            model_name='enquete',
            name='QteCharbonBois',
            field=models.IntegerField(default=0, help_text='la quantité approximative de charbon de bois en kg/mois '),
        ),
        migrations.AddField(
            model_name='enquete',
            name='QteDechetsVeget',
            field=models.IntegerField(default=0, help_text='la quantité approximative de déchets végétaux en kg/mois '),
        ),
        migrations.AddField(
            model_name='enquete',
            name='QteResiduAgric',
            field=models.IntegerField(default=0, help_text='la quantité approximative de résidus agricoles en kg/mois '),
        ),
        migrations.AddField(
            model_name='enquete',
            name='changerEnergie',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='nbPersFoyer',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7 et plus', '7 et plus')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='raisonUsage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='revMensuel',
            field=models.CharField(choices=[('moins de 500 TND', 'Moins de 500 TND'), ('500 - 1000 TND', '500 - 1000 TND'), ('1000 - 1500 TND', '1000 - 1500 TND'), ('plus de 1500 TND', 'Plus de 1500 TND')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='sourceAlter',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='sourceApprov',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='statutResidence',
            field=models.CharField(choices=[('urbain', 'Urbain'), ('rural', 'Rural')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='typeBiomasse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='usageBiomasse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DetailsEnquete',
        ),
    ]
