# Generated by Django 5.0.7 on 2024-07-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0003_enquete_usagebiomasse_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='localite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes', to='enquete.localite'),
        ),
    ]
