# Generated by Django 5.0.7 on 2024-07-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0004_alter_enquete_localite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gouvernorat',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
