# Generated by Django 5.0.7 on 2024-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_alter_delegation_libelle_alter_gouvernorat_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='GPSlocation',
        ),
        migrations.AddField(
            model_name='enquete',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
