# Generated by Django 5.0.7 on 2024-07-30 08:09
from django.db import migrations, models

def merge_agent_data(apps, schema_editor):
    User = apps.get_model('enquete', 'User')
    Agent = apps.get_model('enquete', 'Agent')

    for agent in Agent.objects.all():
        user = agent.user
        user.gouvernorat = agent.gouvernorat
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0006_remove_enquete_gpslocation_enquete_latitude_and_more')
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gouvernorat',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.RunPython(merge_agent_data),
    ]

