# Generated by Django 5.0.7 on 2024-07-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0007_merge_agent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='agent',
        ),
        migrations.AddField(
            model_name='enquete',
            name='User',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='gouvernorat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquete.gouvernorat'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
